export const COMMUNICATION_COSTS_REQUEST = "communications/COSTS_REQUEST";
export type T_COMMUNCATION_COSTS_REQUEST = typeof COMMUNICATION_COSTS_REQUEST;
export const COMMUNICATION_COSTS_SUCCESS = "communications/COSTS_SUCCESS";
export type T_COMMUNICATION_COSTS_SUCCESS = typeof COMMUNICATION_COSTS_SUCCESS;

export const COMMUNICATION_COSTS_SET_ACTIVE_CYCLE = "communications/SET_CYCLE";
export type T_COMMUNICATION_COSTS_SET_ACTIVE_CYCLE = typeof COMMUNICATION_COSTS_SET_ACTIVE_CYCLE;
