export const SET_QUERY = "search/SET_QUERY";
export type T_SET_QUERY = typeof SET_QUERY;

export const SET_PARTY_AFFILIATION = "search/SET_PARTY_AFFILIATION";
export type T_SET_PARTY_AFFILIATION = typeof SET_PARTY_AFFILIATION;

export const SET_OFFICE = "search/SET_OFFICE";
export type T_SET_OFFICE = typeof SET_OFFICE;

export const SET_SEARCH_PROCESSING = "search/SET_SEARCH_PROCESSING";
export type T_SET_SEARCH_PROCESSING = typeof SET_SEARCH_PROCESSING;

export const CANDIDATE_SEARCH_REQUEST = "search/CANDIDATE_SEARCH_REQUEST";
export type T_CANDIDATE_SEARCH_REQUEST = typeof CANDIDATE_SEARCH_REQUEST;

export const CANDIDATE_SEARCH_SUCCESS = "search/CANDIDATE_SEARCH_SUCCESS";
export type T_CANDIDATE_SEARCH_SUCCESS = typeof CANDIDATE_SEARCH_SUCCESS;

export const SET_PAGINATION = "search/SET_PAGINATION";
export type T_SET_PAGINATION = typeof SET_PAGINATION;

export const NEXT_PAGE_REQUEST = "search/NEXT_PAGE_REQUEST";
export type T_NEXT_PAGE_REQUEST = typeof NEXT_PAGE_REQUEST;

export const PREV_PAGE_REQUEST = "search/PREV_PAGE_REQUEST";
export type T_PREV_PAGE_REQUEST = typeof PREV_PAGE_REQUEST;
