export const ELECTIONEERING_TOTALS_REQUEST = "electioneering/TOTALS_REQUEST";
export type T_ELECTIONEERING_TOTALS_REQUEST = typeof ELECTIONEERING_TOTALS_REQUEST;
export const ELECTIONEERING_TOTALS_SUCCESS = "electioneering/TOTALS_SUCCESS";
export type T_ELECTIONEERING_TOTALS_SUCCESS = typeof ELECTIONEERING_TOTALS_SUCCESS;
