export const SET_ACTIVE_CANDIDATE = "candidateHub/SET_ACTIVE_CANDIDATE";
export type T_SET_ACTIVE_CANDIDATE = typeof SET_ACTIVE_CANDIDATE;

export const ACTIVE_CANDIDATE_INFO_REQUEST =
  "candidateHub/ACTIVE_CANDIDATE_INFO_REQUEST";
export type T_ACTIVE_CANDIDATE_INFO_REQUEST = typeof ACTIVE_CANDIDATE_INFO_REQUEST;
export const ACTIVE_CANDIDATE_INFO_SUCCESS =
  "candidateHub/ACTIVE_CANDIDATE_INFO_SUCCESS";
export type T_ACTIVE_CANDIDATE_INFO_SUCCESS = typeof ACTIVE_CANDIDATE_INFO_SUCCESS;

export const SET_CANDIDATE_HUB_PROCESSING = "candidateHub/SET_PROCESSING";
export type T_SET_CANDIDATE_HUB_PROCESSING = typeof SET_CANDIDATE_HUB_PROCESSING;
